# Generated by Django 4.1.2 on 2022-12-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("passwd", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=10)),
                ("reg_date", models.DateField(blank=True, null=True)),
            ],
            options={"db_table": "member", "managed": False,},
        ),
    ]
